### PR TITLE
custom dimensions and metrics should be set on additional account nam…

### PR DESCRIPTION
**Pull request by mhmaguire**
…es as well as default tracker

I'm using additionalAccountNames to fire events on multiple trackers. If I set up a custom dimension I want it to be set on all trackers.

### CODE REVIEW

**Comment by DanWilkerson** [comment]
Hm, I understand what you're saying, but I'm not sure this should be the default mechanism for handling custom dimensions/multiple accounts. Google Analytics does not behave this way natively; you must set the dimension all all trackers individually. Additionally, CD's are scoped to properties and can have different indices, which could cause undesirable side effects.

Can you describe more about your use case and why you feel this is how it should be handled?

**Comment by mhmaguire** [comment]
I hadn't considered the implications of different indices on different properties. In my use case we are using multiple properties to provide access to various project stakeholders, so we want the data to be identical on all properties.

**Comment by timelf123** [comment]
If the data is identical across properties, why separate them into multiple properties at all?

**Comment by DanWilkerson** [comment]
@timelf123 Typically because you're running a rollup tracker in parallel with your domain-specific tracker. Any objections to closing this?

**Comment by timelf123** [comment]
No objections here @DanWilkerson

**Pull request closed without merging**
