### PR TITLE
Refactor, added Classic User TImings, added duplication configs, added docs

### LINKED ISSUE #46: additional trackers (additionalAccountNames) not used by setUserProperties
setUserProperties sends custom dimensions/metrics to the default tracker, not the additional ones configured by additionalAccountNames

### LINKED ISSUE #69: Events are if/else for UA/Classic, Pageviews do both
If both classic and universal analytics are on the page, pageviews will be dispatched to both systems. Events do one or the other. This behavior should be standardized.

### PR DESCRIPTION
**Pull request by DanWilkerson**
Refactored core code to use a single handler for dispatching hits (dispatchGaHit) and remove the need to check the version in each individual api handler. Changed the model to format every hit in the UA style and then transpose to the Classic style in the handler.

Added a configuration option to specify which hits to duplicate/not duplicate. Defaults are set to mirror current default behavior.

Bumped minor to 0.3.0. Will need to re-bump if #67 is accepted before/after.

Should close #46, #69, #70, and #26.

### CODE REVIEW

**Comment by timelf123** [comment]
Whoops, merged the transaction one already. LGTM after conflicts solved. Can these two just share the same minor?

**Comment by DanWilkerson** [comment]
@timelf I'd like to adjust the ecommerce code to use the same dispatchToGa and additionalAccountsHitTypes w/ this PR. Can I push another commit tonight without bumping, you think?

**Comment by timelf123** [comment]
Sounds good to me since we haven't published anything to npm or pushed any tags

**Comment by DanWilkerson** [comment]
Dug myself in a bit of a hole here without realizing it - may take another day to get this ironed out.

**Comment by DanWilkerson** [comment]
Okay, take a look and let me know if it's good to merge in @timelf123

**Comment by timelf123** [comment]
Still conflicts with master @DanWilkerson

**Comment by DanWilkerson** [comment]
Whoops, so there are. Fixed and merged!

**Comment by timelf123** [comment]
Does this need to be built/tagged/published?

**Comment by DanWilkerson** [comment]
Yes, does need to be published - I rebuilt before pulling again. I have a release drafted with these notes:
v0.3.0 
- Added Ecommerce tracking
- Added support for multiple trackers for all hit types
- Retooled Custom Dimension iteration and added support for CDs on Pageview hits
- Refactored code to use dispatchToGa handler

LGTY? I can publish immediately.

**Comment by timelf123** [comment]
LGTM  @DanWilkerson

Nice work

**Pull request merged**
