### PR TITLE
use Error object in exception tracking

### PR DESCRIPTION
**Pull request by odedniv**
I can't see anywhere a usage of angulartics' exception tracking mechanism, so I thought a good standard to start with (for other modules as well as GA) is to send the [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) object.

Few notes:
* I use `toString()` which combines `message` and `name` properties an `Error` object has, it doesn't have `description`. Also, `toString()` works for strings when someone throws a string directly: `throw "There was a problem!"`, so no problems there.
* I don't see a reason for exception tracking to add extra dimensions & metrics, but I'm a noob in GA so please enlighten me.

This should be merged before (or in the same time of) merging angulartics/angulartics#461, which uses this new standard.

### CODE REVIEW

**Comment by DanWilkerson** [comment]
Hm, this makes much more sense to me semantically. I think properties/description are just some accidentally inherited semantics. I can't see any reason not to do this.

Per dimensions and metrics, there could still be cause to include them. For example, for many clients, I configure a few standard dimensions that go out with every hit; a standard timestamp, the current GTM version and container ID (obviously doesn't apply here, though), etc. I'd like to see that included. How could we do that in a simple way? Bolt those properties on to the Error object?

**Comment by odedniv** [comment]
No, I wouldn't change the error object given from the outside, I'll update the PR to use the dimensions and error details in a new object. Will comment here when it's done.

**Comment by odedniv** [comment]
Oh wait, I see the problem... Not sure how you can pass this, especially when this is done automatically (angulartics/angulartics#461). Are you sure those properties make sense with error tracking? Do you really need to know *who* the guy is when debugging?

Maybe those properties need to be set globally? If you say they should go with every event, do you really want to pass them every time?

**Comment by odedniv** [comment]
One more thing: when merging this the major version should probably be increased as this is a breaking change.

**Comment by DanWilkerson** [comment]
Yes, you're correct. I put some more thought into it, and I think I'm overthinking it. Probably 99.9% of our user base won't need custom dimensions w/ errors. I've refactored my GTM pull to mirror this, too. Good stuff.

**Pull request merged**
