### PR TITLE
Add exceptionTrack implementation.

### PR DESCRIPTION
**Pull request by andr3medeiros**
Implementation of the 'exceptionTrack' event in https://github.com/angulartics/angulartics 'knownHandlers', as discussed in https://github.com/angulartics/angulartics/pull/313.

### CODE REVIEW

**Comment by timelf123** [comment]
thank you!

**Comment by DanWilkerson** [comment]
On further review, the Exception hit type doesn't appear to be available for reporting within the interface for Web-type Views, meaning this data wouldn't be accessible at all. Exception hits are native app-specific, it appears. If I'm missing something obvious, please let me know.

If this is the case, however, I'd suggest that we support exception tracking through events, although I'd recommend using the name trackError instead of exception, to prevent this type of confusion.

**Comment by Emeegeemee** [comment]
I did a quick search and it looks like you need to create a custom report to see the data, but this stackoverflow is a little old so I'm not sure if its still applicable.

http://stackoverflow.com/questions/21718481/report-for-exceptions-from-google-analytics-analytics-js-exception-tracking

**Comment by DanWilkerson** [comment]
In my experience it's not a good idea to conflate Mobile-modeled data with Web-modeled data, at least not at the moment. For example, sending in mobile hits to a Web-type view will trigger all kinds of irritating notifications in the interface that can cause some panic. I'm not sure these hits would do the same thing, but my instinct is that given this data isn't available in the interface w/o rolling a Custom Report, I'd recommend against using this hit type. We'd be better served making a convenience function that generated an Event, instead, [which is what I recommend doing](http://danwilkerson.com/google-analytics-error-tracking-guide/). I'm going to remove this in a future PR, but I'll pull it in from myself for further opinions.

**Pull request merged**
