### PR TITLE
Rename angulartics-google-analytics.js to angulartics-ga.js

### LINKED ISSUE #13: 'google-analytics' string in filename causes plugin to be filtered by various browser privacy exensions
At least one Chrome privacy extension, uBlock origin, blocks any URL containing the string 'google-analytics', and I imagine other extensions do as well, since that is the name of the google analytics server domain.

You may want to consider a name change as this can be a frustrating problem to troubleshoot, and if developers aren't concatenating/uglifying their applications, total app failure for users who have privacy extensions installed.

### PR DESCRIPTION
**Pull request by timlevett**
Similarly to how one fixed https://github.com/angulartics/angulartics/issues/58 this change should Resolve #13.

### CODE REVIEW

**Comment by vertein** [comment]
:+1: Thanks @timlevett!  This would help us out a lot.

**Comment by apetro** [comment]
:+1: . Would resolve [a hang-forever-loading graceless failure in MyUW](https://kb.wisc.edu/myuw/page.php?id=60697).

**Comment by ahoffmann-wi** [comment]
This will break again if the ad blocker blacklists are updated to include `angulartics-ga.js`. I'm not really sure what other solution there is, though.

**Comment by timlevett** [comment]
The adblock program blocks anything that contains `google_analytics`. You are correct, if they start blocking `ga` then we could be hurting, but ga seems generic enough that it may create other issues for them.

**Comment by timelf123** [comment]
I'll cut a release ASAP with this change. If you run into blacklist issues again, please file a new issue.

**Comment by timlevett** [comment]
Thanks for the update @timelf123 . We very much look forward to the new release.

**Comment by blindstuff** [comment]
Has this been added to a release yet? I'm installing from bower and I'm getting the old naming.

**Comment by darkmavis1980** [comment]
I'm having the same issue, I guess it's also the folder name that gives the issue

**Comment by timlevett** [comment]
Interesting, I can check with our support, see if they are still getting cases.

**Comment by blindstuff** [comment]
@timlevett I was also getting this error, the folder name is blocked as well. 

@darkmavis1980, While the issue is solved, you can work around it by using a build process to rename or to combine multiple library dependencies, but if you do a direct install from bower, it will get blocked.

**Pull request merged**
