### PR TITLE
Refactored trackException

### PR DESCRIPTION
**Pull request by DanWilkerson**
Google Analytics doesn't have a standard report for Exception hit types in web properties. The hit type is listed in the docs, but is technically for use with mobile app tracking.

This PR switches to using an Event, which is does show up in the standard reports.

Events also support up to 500 bytes of text vs the 150 bytes offered for Exception events. This would break the previous implementation.

### CODE REVIEW

**Comment by odedniv** [comment]
Hey, where is exceptionTrack invoked? I can't find it in angulartics code (and no reply there, see #450).

Do I need to manually invoke this in my app?

Thanks!

**Comment by DanWilkerson** [comment]
Yes, exceptionTrack doesn't do anything automagically; you must call it manually.

**Comment by DanWilkerson** [comment]
@timelf123 Any thoughts on this? It is a breaking change, but is a better solution IMO.

**Comment by odedniv** [comment]
Can you give a usage example? I'll add a PR to the readme.
I want to make sure I do this right and I think this out to be documented.

(Asking you because I didn't get a reply on the main repo)

**Comment by timelf123** [comment]
I'm cool with merging this @DanWilkerson

**Comment by andr3medeiros** [comment]
Sorry for the late comment but, can we filter by exception type at analytics site? Or will it done by searching for some exception related property through the events?

**Comment by DanWilkerson** [comment]
@andr3medeiros Not in this form, but @odedniv has a better PR in that would allow for that, albeit by using the search feature in GA.

**Pull request merged**
